spring: 
  thymeleaf:
    cache: false
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootsecuritydemo2?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: li220
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true  
